// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pulse.Api.Data;

#nullable disable

namespace Pulse.Api.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    partial class PulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Api.Models.DailySession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContextEnergy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContextSleep")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContextSocial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailySessions");
                });

            modelBuilder.Entity("Pulse.Api.Models.EmotionCard", b =>
                {
                    b.Property<Guid>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardId");

                    b.ToTable("EmotionCards");

                    b.HasData(
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Category = "HighPositive",
                            Description = "Feeling intensely enthusiastic and eager.",
                            Emoji = "⚡",
                            Name = "Excited"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Category = "HighPositive",
                            Description = "Feeling mentally lifted and creatively energised.",
                            Emoji = "✨",
                            Name = "Inspired"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Category = "HighPositive",
                            Description = "Feeling pleased with yourself or something you achieved.",
                            Emoji = "🏆",
                            Name = "Proud"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Category = "HighPositive",
                            Description = "Feeling thankful and appreciative.",
                            Emoji = "🙏",
                            Name = "Grateful"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Category = "HighPositive",
                            Description = "Feeling full of energy and ready to act.",
                            Emoji = "🔥",
                            Name = "Energised"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111106"),
                            Category = "HighPositive",
                            Description = "Feeling deeply happy and uplifted.",
                            Emoji = "😄",
                            Name = "Joyful"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111107"),
                            Category = "HighPositive",
                            Description = "Feeling sure of yourself and your ability.",
                            Emoji = "💪",
                            Name = "Confident"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111108"),
                            Category = "HighPositive",
                            Description = "Feeling light-hearted and fun-loving.",
                            Emoji = "🎉",
                            Name = "Playful"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111109"),
                            Category = "HighPositive",
                            Description = "Feeling positive about what lies ahead.",
                            Emoji = "🌱",
                            Name = "Hopeful"
                        },
                        new
                        {
                            CardId = new Guid("11111111-1111-1111-1111-111111111110"),
                            Category = "HighPositive",
                            Description = "Feeling driven to take action.",
                            Emoji = "🎯",
                            Name = "Motivated"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Category = "LowPositive",
                            Description = "Feeling peaceful and steady.",
                            Emoji = "🌊",
                            Name = "Calm"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Category = "LowPositive",
                            Description = "Feeling quietly satisfied with the moment.",
                            Emoji = "☀️",
                            Name = "Content"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Category = "LowPositive",
                            Description = "Feeling free from stress or conflict.",
                            Emoji = "🕊️",
                            Name = "Peaceful"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Category = "LowPositive",
                            Description = "Feeling secure and protected.",
                            Emoji = "🏡",
                            Name = "Safe"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222205"),
                            Category = "LowPositive",
                            Description = "Feeling welcomed and valued as you are.",
                            Emoji = "🤝",
                            Name = "Accepted"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222206"),
                            Category = "LowPositive",
                            Description = "Feeling warm, comfortable, and settled.",
                            Emoji = "🍵",
                            Name = "Cosy"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222207"),
                            Category = "LowPositive",
                            Description = "Feeling warmly reflective about the past.",
                            Emoji = "🌅",
                            Name = "Nostalgic"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222208"),
                            Category = "LowPositive",
                            Description = "Feeling soft-hearted and emotionally open.",
                            Emoji = "🌸",
                            Name = "Tender"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222209"),
                            Category = "LowPositive",
                            Description = "Feeling stable, centred, and present.",
                            Emoji = "🌍",
                            Name = "Grounded"
                        },
                        new
                        {
                            CardId = new Guid("22222222-2222-2222-2222-222222222210"),
                            Category = "LowPositive",
                            Description = "Feeling complete and deeply satisfied.",
                            Emoji = "✅",
                            Name = "Fulfilled"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Category = "HighNegative",
                            Description = "Feeling worried, tense, or uneasy.",
                            Emoji = "😰",
                            Name = "Anxious"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Category = "HighNegative",
                            Description = "Feeling overloaded and emotionally stretched.",
                            Emoji = "🌀",
                            Name = "Overwhelmed"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333303"),
                            Category = "HighNegative",
                            Description = "Feeling strong frustration or irritation.",
                            Emoji = "😤",
                            Name = "Angry"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333304"),
                            Category = "HighNegative",
                            Description = "Feeling unable to relax or settle.",
                            Emoji = "😬",
                            Name = "Restless"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333305"),
                            Category = "HighNegative",
                            Description = "Feeling mentally pressured and strained.",
                            Emoji = "💢",
                            Name = "Stressed"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333306"),
                            Category = "HighNegative",
                            Description = "Feeling envious or threatened by comparison.",
                            Emoji = "👁️",
                            Name = "Jealous"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333307"),
                            Category = "HighNegative",
                            Description = "Feeling a sudden rush of fear or alarm.",
                            Emoji = "😱",
                            Name = "Panicked"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333308"),
                            Category = "HighNegative",
                            Description = "Feeling annoyed and easily provoked.",
                            Emoji = "😠",
                            Name = "Irritated"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333309"),
                            Category = "HighNegative",
                            Description = "Feeling chaotic, rushed, and out of control.",
                            Emoji = "🏃",
                            Name = "Frantic"
                        },
                        new
                        {
                            CardId = new Guid("33333333-3333-3333-3333-333333333310"),
                            Category = "HighNegative",
                            Description = "Feeling guarded or ready to protect yourself.",
                            Emoji = "🛡️",
                            Name = "Defensive"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444401"),
                            Category = "LowNegative",
                            Description = "Feeling down or emotionally heavy.",
                            Emoji = "😔",
                            Name = "Sad"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444402"),
                            Category = "LowNegative",
                            Description = "Feeling hollow or emotionally drained.",
                            Emoji = "🕳️",
                            Name = "Empty"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444403"),
                            Category = "LowNegative",
                            Description = "Feeling disconnected from emotion.",
                            Emoji = "🌫️",
                            Name = "Numb"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444404"),
                            Category = "LowNegative",
                            Description = "Feeling isolated or emotionally alone.",
                            Emoji = "🚶",
                            Name = "Lonely"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444405"),
                            Category = "LowNegative",
                            Description = "Feeling like things will not improve.",
                            Emoji = "🌧️",
                            Name = "Hopeless"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444406"),
                            Category = "LowNegative",
                            Description = "Feeling exhausted and depleted.",
                            Emoji = "🪫",
                            Name = "Drained"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444407"),
                            Category = "LowNegative",
                            Description = "Feeling detached from people or the moment.",
                            Emoji = "📵",
                            Name = "Disconnected"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444408"),
                            Category = "LowNegative",
                            Description = "Feeling embarrassed or deeply self-critical.",
                            Emoji = "😞",
                            Name = "Ashamed"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444409"),
                            Category = "LowNegative",
                            Description = "Feeling unstimulated or uninterested.",
                            Emoji = "😑",
                            Name = "Bored"
                        },
                        new
                        {
                            CardId = new Guid("44444444-4444-4444-4444-444444444410"),
                            Category = "LowNegative",
                            Description = "Feeling unseen or overlooked.",
                            Emoji = "👻",
                            Name = "Invisible"
                        });
                });

            modelBuilder.Entity("Pulse.Api.Models.SessionSwipe", b =>
                {
                    b.Property<Guid>("SwipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SwipedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SwipeId");

                    b.HasIndex("CardId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionSwipes");
                });

            modelBuilder.Entity("Pulse.Api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("APNSToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarColour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FCMToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("NotificationTime")
                        .HasColumnType("time");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pulse.Api.Models.DailySession", b =>
                {
                    b.HasOne("Pulse.Api.Models.User", "User")
                        .WithMany("DailySessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pulse.Api.Models.SessionSwipe", b =>
                {
                    b.HasOne("Pulse.Api.Models.EmotionCard", "EmotionCard")
                        .WithMany("SessionSwipes")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pulse.Api.Models.DailySession", "DailySession")
                        .WithMany("SessionSwipes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailySession");

                    b.Navigation("EmotionCard");
                });

            modelBuilder.Entity("Pulse.Api.Models.DailySession", b =>
                {
                    b.Navigation("SessionSwipes");
                });

            modelBuilder.Entity("Pulse.Api.Models.EmotionCard", b =>
                {
                    b.Navigation("SessionSwipes");
                });

            modelBuilder.Entity("Pulse.Api.Models.User", b =>
                {
                    b.Navigation("DailySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
